# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "unitTesting"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path:
          ./backend/package-lock.json
          ./frontend/package-lock.json
          
    - name: install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: run backend test
      working-directory: ./backend
      env: 
        MONGODB_URI: "mongodb://localhost:27017/test_db"
        JWT_SECRET: "test_secret"
        OPENAI_API_KEY: "dummy"
      run: npm test
        
    - name: install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: build front
      working-directory: ./frontend
      run: npm run build
